
import javax.swing.JOptionPane;


public class CUSTOMER extends javax.swing.JFrame {

    /**
     * Creates new form CUSTOMER
     */
    public CUSTOMER() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CLbgpanel = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        CLview = new javax.swing.JButton();
        CLreturn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CLcreate = new javax.swing.JButton();
        CLexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CUSTOMER_TAB");

        jLabel1.setText("CUSTOMER ACCESS");

        CLview.setText("VIEW DEPARTMENTS");
        CLview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLviewActionPerformed(evt);
            }
        });

        CLreturn.setText("RETURN TO LOG IN");
        CLreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLreturnActionPerformed(evt);
            }
        });

        jLabel2.setText("*\"please contact an admin if you want to change something to your account\"*");

        CLcreate.setText("CREATE NEW ACCOUNT");
        CLcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLcreateActionPerformed(evt);
            }
        });

        CLexit.setText("EXIT");
        CLexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CLbgpanelLayout = new javax.swing.GroupLayout(CLbgpanel);
        CLbgpanel.setLayout(CLbgpanelLayout);
        CLbgpanelLayout.setHorizontalGroup(
            CLbgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLbgpanelLayout.createSequentialGroup()
                .addGroup(CLbgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CLbgpanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1))
                    .addGroup(CLbgpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(CLbgpanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(CLbgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CLreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CLview, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CLcreate, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CLbgpanelLayout.createSequentialGroup()
                                .addComponent(CLexit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CLbgpanelLayout.setVerticalGroup(
            CLbgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CLbgpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(CLview, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CLreturn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CLcreate, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CLexit)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CLbgpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CLbgpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CLviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLviewActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null," Departments:\n Hardware\nFood\nSecurity\nClothing" , "available departments",JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_CLviewActionPerformed

    private void CLreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLreturnActionPerformed
        // TODO add your handling code here:
            new LoginFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_CLreturnActionPerformed

    private void CLcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLcreateActionPerformed
        // TODO add your handling code here:
        new REGISTER().setVisible(true);
        dispose();
    }//GEN-LAST:event_CLcreateActionPerformed

    private void CLexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLexitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "thank you for using the app!", "Hope to see ya again!", JOptionPane.PLAIN_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_CLexitActionPerformed

 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel CLbgpanel;
    public javax.swing.JButton CLcreate;
    public javax.swing.JButton CLexit;
    public javax.swing.JButton CLreturn;
    public javax.swing.JButton CLview;
    public javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
